### ISSUE TITLE
error in browser console

### ISSUE THREAD

**Issue by Faris90** [CommunityDiep/client#4] opened 2018-04-23 18:49 UTC
```
Uncaught TypeError: Cannot read property 'length' of undefined
at drawTank (functions.js:32)
at Player.draw (client.js:207)
at loopy (client.js:440)
```

**Comment by haykam821** [comment] 2018-04-23 18:52
Duplicate of your other issue, #3, where you posted the exact same issue.

**Closed as completed by haykam821** 2018-04-23 18:52 UTC
